version: "3.9"

services:
  backend_server:
    restart: always    
    command: npm start
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:80"

